const COIN_SCALE = 1000n;
const TRANSFER_FEE_BPS = 50n;
const TRANSFER_RESERVE_BPS = 30n;
const TRANSFER_BURN_BPS = 20n;
const MIN_TRANSFER_MICRO = 1n;
const MIN_TRANSFER_FEE_MICRO = 1n;
const DAILY_TRANSFER_LIMIT_COIN = 100000n;
const DAILY_TRANSFER_LIMIT_MICRO = DAILY_TRANSFER_LIMIT_COIN * COIN_SCALE;

const SYSTEM_WALLET_CODES = {
  TREASURY: 'TREASURY',
  DEVELOPER_RESERVE: 'DEVELOPER_RESERVE',
  BURN_WALLET: 'BURN_WALLET',
  PAYMENT_CLEARING: 'PAYMENT_CLEARING',
};

module.exports = {
  COIN_SCALE,
  TRANSFER_FEE_BPS,
  TRANSFER_RESERVE_BPS,
  TRANSFER_BURN_BPS,
  MIN_TRANSFER_MICRO,
  MIN_TRANSFER_FEE_MICRO,
  DAILY_TRANSFER_LIMIT_MICRO,
  SYSTEM_WALLET_CODES,
};

